---
title: "03_generate_FoodTrees"
output: html_document
date: "2025-10-10"
---
# ===============================================================================================================
# Generate foodtrees for the NHANES mixed meals and ingredients features
# Created on 02/16/2023 by Rie Sadohara
# Modified on 11/20/2025 by Jules Larke
# ===============================================================================================================

```{r}
# Load the packages/scripts necessary for tree building, and if it is not installed, install it.
if (!require("reshape2", quietly = TRUE))install.packages("reshape2")
# Load the data.tree package necessary for newick.tree.r, and if it is not installed, install it. 
if (!require("data.tree", quietly = TRUE))install.packages("data.tree")

# Load source scripts
source("../../diet_diver_lib/Food_tree_scripts/newick.tree.r")
source("../../diet_diver_lib/Food_tree_scripts/make.food.tree.r") # This needs 'newick.tree.r' already loaded.
source("../../diet_diver_lib/Food_tree_scripts/make.food.ifc.r")

# create directory to save foodtree outputs
dir.create("../../data/02/foodtree_out")
```

```{r}
# ===============================================================================================================
# Create Mixed Meals Food Tree
# ===============================================================================================================

# Create foodtree with the foods classified at a desired level of classification (Lv. 1-5).
# "NodeLabelsMCT.txt" has a list of levels and mixed meal names, which comes with the DietDiveR package.
MakeFoodTree(nodes_fn= "../../data/02/NodeLabelsMCT.txt", 
             addl_foods_fn = NULL,
             num_levels = 6,
             food_database_fn =   "../../data/02/wweia_foodcode_taxa_clean.txt",  
             output_tree_fn =     "../../data/02/foodtree_out/wweia_foodcode_tree.nwk", 
             output_taxonomy_fn = "../../data/02/foodtree_out/wweia_foodcode_taxonomy.txt"
)

# nodes_fn:           The food level (node) information for each food item.
# num_levels:         Number of food levels (1 - 6) to save.
# food_database_fn:   Your food item data.
# addl_foods_fn:      List of foods not present in the list can be added. NULL by default.
# output_tree_fn:     Output tree file name. Should end with ".nwk"
# output_taxonomy_fn: Output taxonomy file (to be used later) name.  
```

```{r}
# ===============================================================================================================
# Create Ingredients Food Tree - IR dataset
# ===============================================================================================================

# Create foodtree with the foods classified at a desired level of classification (Lv. 1-5).
# "node_labels_clean.txt" has a list of levels and ingredient names derived from the FNDDS
MakeFoodTree(nodes_fn= "../../data/02/node_labels_clean.txt", 
             addl_foods_fn = NULL,
             num_levels = 5,
             food_database_fn =   "../../data/02/ir_ingredient_taxa_clean.txt",  
             output_tree_fn =     "../../data/02/foodtree_out/ir_ingredient_tree.nwk", 
             output_taxonomy_fn = "../../data/02/foodtree_out/ir_ingredient_taxonomy.txt"
)

```

```{r}
# ===============================================================================================================
# Create Ingredients Food Tree - Polyphenol dataset
# ===============================================================================================================

# Create foodtree with the foods classified at a desired level of classification (Lv. 1-5).
# "fda_node_labels_clean.txt" has a list of levels and ingredient names derived from the FDA-FDD 
MakeFoodTree(nodes_fn= "../../data/02/node_labels_clean.txt", 
             addl_foods_fn = NULL,
             num_levels = 5,
             food_database_fn =   "../../data/02/poly_ingredient_taxa_clean.txt",  
             output_tree_fn =     "../../data/02/foodtree_out/poly_ingredient_tree.nwk", 
             output_taxonomy_fn = "../../data/02/foodtree_out/poly_ingredient_taxonomy.txt"
)
```

```{r}
# --------------------------------------------------------------------------------------------------------------
# Generate IFC tables for downstream analyses; IT MAY TAKE SOME TIME.
# It is OK to see the following warning message:
# In write.table(fiber.ifc, output_fn, sep = "\t", quote = F, append = TRUE) :
# appending column names to file.

# load libraries
require(data.table)
library(dplyr)
```

```{r}
# load in data for Mixed Meals wide format and wrangle
recalls <- data.table::fread('../../data/01/insulin_resistance/wweia_mixed_meals_long.tsv', header=T)
taxa = read.csv("../../data/02/wweia_foodcode_taxa_clean.txt", sep="\t")
colnames(taxa)[1] = 'foodcode'
recalls_taxa <- merge(recalls, taxa, by = "foodcode")

# sum total grams of each food eaten per subject
otu.total <- aggregate(foodcode_intake_g_per_1000kcal ~ SEQN + FoodID, data=recalls_taxa, FUN="sum")
colnames(otu.total)<-c("SEQN", "FoodID", "FoodAmt") #rename columns for creating otu_table
write.table(otu.total, "../../data/taxahfe/foodcode_recalls_otu_table.tsv", sep="\t", row.names=F, quote=F)

# read in taxonomy produced above to clean up extra text description at end (removes the appended leaf name so the tree appears correct)
taxonomy <- data.table::fread('../../data/02/foodtree_out/wweia_foodcode_taxonomy.txt', header=T)
taxonomy$taxonomy <- gsub(";[^;]+$", "", taxonomy$taxonomy)
write.table(taxonomy, "../../data/02/foodtree_out/wweia_foodcode_taxonomy_clean.txt", sep="\t", row.names=F, quote=F)
```

```{r}
# Make the standard IFC table with data in gram weights of food.
# For the food_records_fn argument, you need to supply 'sel.food.records' file that have 'FoodAmt' column.     
MakeFoodIfc(food_records_fn=  "../../data/taxahfe/foodcode_recalls_otu_table.tsv",   
            food_record_id =  "SEQN",                              
            food_taxonomy_fn= "../../data/02/foodtree_out/wweia_foodcode_taxonomy_clean.txt",       
            output_fn =       "../../data/taxahfe/foodcode_otu_table.txt")  

```

```{r}
# load in IR data for Ingredients and wrangle
recalls <- data.table::fread('../../data/01/insulin_resistance/wweia_ingredients_long.tsv', header=T)
taxa = read.csv("../../data/02/ir_ingredient_taxa_clean.txt", sep="\t")
colnames(taxa)[3] = 'ingred_code'

# write metadata (target + covariates) for taxaHFE (this output will be used for each IR diet dataset (Mixed meals, Ingredients, FPED))
metadata <- recalls %>% select(!c(ingred_code, ingred_desc, ingredient_intake_g_per_1000kcal))
metadata = distinct(metadata, SEQN, .keep_all=TRUE)
metadata$ir <- ifelse(metadata$ir == 1, yes = 'yes', no = 'no')
meta_ir <- metadata %>% select(!c(crp))
write.table(meta_ir, "../../data/taxahfe/metadata_ir.tsv", sep="\t", row.names=F, quote=F)

# merge recalls with taxonomy
recalls_taxa <- merge(recalls, taxa, by = "ingred_code")

# sum total grams of each food eaten per subject
otu.total <- aggregate(ingredient_intake_g_per_1000kcal ~ SEQN + FoodID, data=recalls_taxa, FUN="sum")
colnames(otu.total)<-c("SEQN", "FoodID", "FoodAmt") #rename columns for creating otu_table
write.table(otu.total, "../../data/taxahfe/ir_recalls_otu_table.tsv", sep="\t", row.names=F, quote=F)

# read in taxonomy produced above to clean up extra text description at end (removes the appended leaf name so the tree appears correct)
taxonomy <- data.table::fread('../../data/02/foodtree_out/ir_ingredient_taxonomy.txt', header=T)
taxonomy$taxonomy <- gsub(";[^;]+$", "", taxonomy$taxonomy)
write.table(taxonomy, "../../data/02/foodtree_out/ir_ingredient_taxonomy_clean.txt", sep="\t", row.names=F, quote=F)
```

```{r}
# Make the standard IFC table with data in gram weights of food.
# For the food_records_fn argument, you need to supply 'sel.food.records' file that have 'FoodAmt' column.     
MakeFoodIfc(food_records_fn=  "../../data/taxahfe/ir_recalls_otu_table.tsv",   
            food_record_id =  "SEQN",                              
            food_taxonomy_fn= "../../data/02/foodtree_out/ir_ingredient_taxonomy_clean.txt",       
            output_fn =       "../../data/taxahfe/ir_ingred_otu_table.txt")  
```

```{r}
# load in data for polyphenol Ingredients (FDA descriptions)
recalls <- data.table::fread('../../data/01/polyphenol/poly_ingredients_long.tsv', header=T)

# load taxa data generated above
taxa = read.csv("../../data/02/poly_ingredient_taxa_clean.txt", sep="\t")
colnames(taxa)[3] = 'ingred_code' # rename
recalls_taxa <- merge(recalls, taxa, by = "ingred_code")

# sum total grams of each food eaten per subject
otu.total <- aggregate(ingredient_intake_g_per_1000kcal ~ SEQN + FoodID, data=recalls_taxa, FUN="sum")
colnames(otu.total)<-c("SEQN", "FoodID", "FoodAmt") #rename columns for creating otu_table
write.table(otu.total, "../../data/taxahfe/poly_recalls_otu_table.tsv", sep="\t", row.names=F, quote=F)

# read in taxonomy produced above to clean up extra text description at end (removes the appended leaf name so the tree appears correct)
taxonomy <- data.table::fread('../../data/02/foodtree_out/poly_ingredient_taxonomy.txt', header=T)
taxonomy$taxonomy <- gsub(";[^;]+$", "", taxonomy$taxonomy)
write.table(taxonomy, "../../data/02/foodtree_out/poly_ingredient_taxonomy_clean.txt", sep="\t", row.names=F, quote=F)
```

```{r}
# Make the standard IFC table with data in gram weights of food for the ingredients data with FDA descriptions
# For the food_records_fn argument, you need to supply 'sel.food.records' file that have 'FoodAmt' column.     
MakeFoodIfc(food_records_fn=  "../../data/taxahfe/poly_recalls_otu_table.tsv",   
            food_record_id =  "SEQN",                              
            food_taxonomy_fn= "../../data/02/foodtree_out/poly_ingredient_taxonomy_clean.txt",       
            output_fn =       "../../data/taxahfe/poly_ingred_otu_table.txt")
```